name: PHP Checks

on: [push, pull_request]

jobs:
  tests:
    name: Checks on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1

      - name: Coding standards
        run: composer lint

      - name: Static analysis
        run: composer analyse

      - name: Tests
        run: vendor/bin/phpunit
